### ISSUE TITLE
Support for multi-line literals in .ttl files

### ISSUE THREAD

**Issue by dylan-sa** [OxfordSemantic/vscode-rdfox-rdf#1]
Hi, I'm loving this new extension for VSCode but did encounter a possible bug in .ttl files. Often it's useful to create multi-line quoted literals using triple quotes. The current version of the extension doesn't seem to pick up on these--would it be possible to incorporate support for them?

**Comment by DianaMarksOST** [comment]
Hi, I'm glad you like the extension! Yes, I believe we should be able to add support for multi-line quotes, I will look into it

**Comment by DianaMarksOST** [comment]
@dylan-sa This issue was fixed in commit [375426d](https://github.com/OxfordSemantic/vscode-rdfox-rdf/commit/375426d27188332378360ae565c50801ddd6e333), which has been published in version 1.0.2 of the extension. Please let us know if you find any other bugs (or further problems with multi-line literals)
