### ISSUE TITLE
Feature with .owl files

### ISSUE THREAD

**Issue by Nchrd** [OxfordSemantic/vscode-rdfox-rdf#5]
Hi,
I'm currently working on an ontology using Protégé and I thought of an improvement that could help people who are in the same situation as me: Protégé only saves ontologies that one has created using .owl files. The fact is that you can choose the syntax for writing the ontology in the file and the turtle format is part of it. Do you think you could add support for .owl files? 
Especially since the turtle format is quite readable so it's quite convenient to modify your ontology by hand, which happens quite often with Protégé when you use existing ontologies or pieces of ontologies.

**Comment by DianaMarksOST** [comment]
Hi,

I have looked into this and since the `.owl` file extension is sometimes used for files written in many different syntaxes, I would rather avoid automatically parsing it as Turtle. According to the [spec](https://www.w3.org/TR/turtle/#sec-mediaReg), the only recommended extension for Turtle files is `.ttl`.

There are several ways you can get around your problem:

1. You can save an ontology with the `.ttl` extension from Protege by going to File > Save as..., choosing the Turtle syntax and then manually entering a file name that contains the `.ttl` extension. In my testing, Protege recognises that the file has already been given an extension and skips the `.owl` extension. (Alternatively, you can manually change the name after saving and then re-open the file in Protege)

2. When you open the file in VSCode, on the bar at the very bottom of the window there is the "language mode" VSCode is using for that file. It will try to auto-detect the language for unknown file extensions (in my testing, VSCode assumed the `.owl` file was an XML file). You can click on the "language mode" and then "Select Language Mode" will show up at the top of the window. If you want to configure the language mode for just this file, you can type in "Turtle" and choose that. If you would like to associate all `.owl` files with the Turtle language, you can instead click "Configure File Association for '.owl'..." and choose Turtle there.
